Update requirements.txt
Encounter an error 
ImportError: tokenizers>=0.13.3 is required for a normal functioning of this module, but found tokenizers==0.11.4.

while running python run_localGPT.py

This fixed it